// SOME ACTIONS
// Products
const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
const FETCH_PRODUCT_ID = 'FETCH_PRODUCT_ID';
const CREATE_PRODUCT = 'CREATE_PRODUCT';
// Purchase
const CREATE_PURCHASE_TOKEN = 'CREATE_PURCHASE_TOKEN';
const REMOVE_PURCHASE_TOKEN = 'REMOVE_PURCHASE_TOKEN';
const SEND_PURCHASE = 'BUY_PRODUCT_ID';
const FETCH_PURCHASES = 'FETCH_PURCHASES';
const GET_PURCHASE_TOKEN = 'GET_PURCHASE_TOKEN';
const FETCH_PRODUCT_TOKEN = 'FETCH_PRODUCT_TOKEN';
// Filters
const SET_FILTER = 'SET_FILTER';

export {
  FETCH_PRODUCTS,
  FETCH_PRODUCT_ID,
  CREATE_PRODUCT,
  SEND_PURCHASE,
  CREATE_PURCHASE_TOKEN,
  REMOVE_PURCHASE_TOKEN,
  FETCH_PURCHASES,
  GET_PURCHASE_TOKEN,
  FETCH_PRODUCT_TOKEN,
  SET_FILTER
};